import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import request from "../utils/request";

export default function Home({ results }) {
  console.log("Props recinved", results);
  console.log(
    "APi created",
    `https://api.themoviedb.org/3/${request.fetchTredning.url}`
  );
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  let url = `https://api.themoviedb.org/3/${
    request[genre]?.url ? request[genre]?.url : request.fetchTredning.url
  }`;
  const apiCall = await fetch(url).then((res) => res.json());
  return {
    props: {
      results: apiCall.results,
    },
  };
}
